#!/bin/sh

set -e

#DEBHELPER#

enable_builtin_mibs() {
    if [ -f /etc/default/snmpd ]; then
        sed -i -e '/SNMPDOPTS+=/d' /etc/default/snmpd
    fi
}

case "$1" in
    remove)
        enable_builtin_mibs
    ;;

    purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        :
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
